### ISSUE TITLE
you wouldnt happen to be able to make the w7 fix work with Polybius would you ?

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [CWTesseract/win7fix#2]
https://store.steampowered.com/app/906120/POLYBIUS/

has no w7 support , i recon because of the exact same issue , would appreciate a fix , thanks

**Comment by washingleavesandthensome23-434** [comment]
anybody? would really appreciate it a ton

**Comment by Andoryuuta** [comment]
This repo / fix was put together solely for the game "Cube World" (steam release) -- It likely will not work for any other game without additional work.

**Comment by washingleavesandthensome23-434** [comment]
think you could make it work globally ? would be epic sauce
------- Original Message -------
